
import essences from "@assets/repoe/essences.min.json";
// Generated by https://quicktype.io

export interface Essences {
  "Metadata/Items/Currency/CurrencyEssenceAnger1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnger2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnger3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnger4":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnger5":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnger6":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnguish1":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnguish2":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnguish3":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceAnguish4":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt1":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt2":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt3":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt4":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt5":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt6":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceContempt7":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceDelirium1":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceDoubt1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDoubt2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDoubt3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDoubt4":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDoubt5":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDread1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDread2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceDread3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceEnvy1":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceEnvy2":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceEnvy3":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear1":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear2":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear3":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear4":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear5":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceFear6":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed4":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed5":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed6":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceGreed7":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred1":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred2":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred3":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred4":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred5":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred6":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHatred7":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHorror1":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceHysteria1":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceInsanity1":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceLoathing1":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceLoathing2":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceLoathing3":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceLoathing4":  Essence;
  "Metadata/Items/Currency/CurrencyEssenceMisery1":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceMisery2":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceMisery3":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceRage1":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceRage2":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceRage3":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceRage4":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceRage5":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceScorn1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceScorn2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceScorn3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow1":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow2":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow3":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow4":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow5":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSorrow6":    Essence;
  "Metadata/Items/Currency/CurrencyEssenceSpite1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceSpite2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceSpite3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceSpite4":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceSuffering1": Essence;
  "Metadata/Items/Currency/CurrencyEssenceSuffering2": Essence;
  "Metadata/Items/Currency/CurrencyEssenceSuffering3": Essence;
  "Metadata/Items/Currency/CurrencyEssenceSuffering4": Essence;
  "Metadata/Items/Currency/CurrencyEssenceSuffering5": Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment1":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment2":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment3":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment4":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment5":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceTorment6":   Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe1":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe2":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe3":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe4":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe5":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe6":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWoe7":       Essence;
  "Metadata/Items/Currency/CurrencyEssenceWrath1":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceWrath2":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceWrath3":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceWrath4":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceWrath5":     Essence;
  "Metadata/Items/Currency/CurrencyEssenceZeal1":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceZeal2":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceZeal3":      Essence;
  "Metadata/Items/Currency/CurrencyEssenceZeal4":      Essence;
}

export interface Type {
  is_corruption_only: boolean;
  tier:               number;
}
export interface Essence {
  item_level_restriction: number | null;
  level:                  number;
  mods:                   { [key: string]: string };
  name:                   string;
  spawn_level_max:        number;
  spawn_level_min:        number;
  type:                   Type;
}


export const essenceModToEssence = Object.fromEntries(
  Object.values(essences as Essences).flatMap((ess: Essence)=>Object.values(ess.mods).map(it=>[it, ess]))
)